--CREATE TABLESPACE iolistDB
--DATAFILE 'C:/oraclexe/data/iolist.dbf'
--SIZE 1M AUTOEXTEND ON NEXT 1K;
--
--CREATE USER iouser IDENTIFIED BY iouser
--DEFAULT TABLESPACE iolistDB;
--
--GRANT DBA TO iouser;
--
--DROP USER iouser CASCADE;
--
--DROP TABLESPACE iolistDB
--INCLUDING CONTENTS AND DATAFILES
--CASCADE CONSTRAINTS;

CREATE TABLESPACE iolistDB_2
DATAFILE 'C:/oraclexe/data/iolist_2.dbf'
SIZE 1M AUTOEXTEND ON NEXT 1K;

CREATE USER iouser2 IDENTIFIED BY iouser2
DEFAULT TABLESPACE iolistDB_2;

GRANT DBA TO iouser2;

DROP USER iouser2 CASCADE;

DROP TABLESPACE iolistDB_2
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;